#!/bin/bash

echo "Checking Nginx status every 5 seconds and restarting if not active."

while true
do
    sudo systemctl status nginx > /dev/null 2>&1

    if [ $? -eq 0 ]; then
        echo "Nginx is running."
    else
        echo "Nginx is not running. Restarting Nginx..."
        sudo systemctl start nginx
    fi

    # Wait for 5 seconds before checking again
    sleep 5
done
